import { nanoid } from "nanoid";
import { Atom } from 'lucide-react';

export const books = [
  {
    id: nanoid(),
    Name: "Brief Answers to the Big Questions",
    Author: "Stephen Hawking",
    Price: "$15.99",
    // Image: "https://example.com/briefanswers.jpg",
    Category: "Science",
  },
  {
    id: nanoid(),
    Name: "Sapiens: A Brief History of Humankind",
    Author: "Yuval Noah Harari",
    Price: "$18.99",
    // Image: "https://example.com/sapiens.jpg",
    Category: "Science",
  },
  {
    id: nanoid(),
    Name: "The Girl with the Dragon Tattoo",
    Author: "Stieg Larsson",
    Price: "$9.99",
    // Image: "https://example.com/dragontattoo.jpg",
    Category: "Mystery",
  },
  {
    id: nanoid(),
    Name: "Gone Girl",
    Author: "Gillian Flynn",
    Price: "$12.99",
    // Image: "https://example.com/gonegirl.jpg",
    Category: "Mystery",
  },
  {
    id: nanoid(),
    Name: "1984",
    Author: "George Orwell",
    Price: "$7.99",
    // Image: "https://example.com/1984.jpg",
    Category: "Fiction",
  },
  {
    id: nanoid(),
    Name: "The Great Gatsby",
    Author: "F. Scott Fitzgerald",
    Price: "$14.99",
    // Image: "https://example.com/greatgatsby.jpg",
    Category: "Fiction",
  },
  {
    id: nanoid(),
    Name: "Pride and Prejudice",
    Author: "Jane Austen",
    Price: "$11.99",
    // Image: "https://example.com/prideprejudice.jpg",
    Category: "Romance",
  },
  {
    id: nanoid(),
    Name: "The Notebook",
    Author: "Nicholas Sparks",
    Price: "$15.99",
    // Image: "https://example.com/thenotebook.jpg",
    Category: "Romance",
  },
  {
    id: nanoid(),
    Name: "Guns, Germs, and Steel",
    Author: "Jared Diamond",
    Price: "$17.99",
    // Image: "https://example.com/gunsgermssteel.jpg",
    Category: "History",
  },
  {
    id: nanoid(),
    Name: "The History of the Ancient World",
    Author: "Susan Wise Bauer",
    Price: "$25.99",
    // Image: "https://example.com/ancientworld.jpg",
    Category: "History",
  },
  {
    id: nanoid(),
    Name: "Astrophysics for People in a Hurry",
    Author: "Neil deGrasse Tyson",
    Price: "$18.99",
    // Image: "https://example.com/astrophysics.jpg",
    Category: "Science",
  },
  {
    id: nanoid(),
    Name: "The Silent Patient",
    Author: "Alex Michaelides",
    Price: "$14.99",
    // Image: "https://example.com/silentpatient.jpg",
    Category: "Mystery",
  },
  {
    id: nanoid(),
    Name: "The Alchemist",
    Author: "Paulo Coelho",
    Price: "$15.99",
    // Image: "https://example.com/alchemist.jpg",
    Category: "Fiction",
  },
  {
    id: nanoid(),
    Name: "Me Before You",
    Author: "Jojo Moyes",
    Price: "$12.99",
    // Image: "https://example.com/mebeforeyou.jpg",
    Category: "Romance",
  },
  {
    id: nanoid(),
    Name: "A People's History of the United States",
    Author: "Howard Zinn",
    Price: "$19.99",
    // Image: "https://example.com/peopleshistory.jpg",
    Category: "History",
  },
  {
    id: nanoid(),
    Name: "Why We Sleep: Unlocking the Power of Sleep and Dreams",
    Author: "Matthew Walker",
    Price: "$17.99",
    // Image: "https://example.com/whysleep.jpg",
    Category: "Science",
  },
  {
    id: nanoid(),
    Name: "Big Little Lies",
    Author: "Liane Moriarty",
    Price: "$16.99",
    // Image: "https://example.com/biglittlelies.jpg",
    Category: "Mystery",
  },
  {
    id: nanoid(),
    Name: "The Night Circus",
    Author: "Erin Morgenstern",
    Price: "$14.99",
    // Image: "https://example.com/nightcircus.jpg",
    Category: "Fiction",
  },
  {
    id: nanoid(),
    Name: "Outlander",
    Author: "Diana Gabaldon",
    Price: "$9.99",
    // Image: "https://example.com/outlander.jpg",
    Category: "Romance",
  },
  {
    id: nanoid(),
    Name: "The Guns of August",
    Author: "Barbara W. Tuchman",
    Price: "$22.99",
    // Image: "https://example.com/gunsofaugust.jpg",
    Category: "History",
  },
];